[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "none"
evm_version = "cancun"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/metamorpho-v1.1/lib/openzeppelin-contracts/",
    "morpho-blue/=lib/stakestock-morpho-blue/src/",
    "metamorpho-v1.1/=lib/metamorpho-v1.1/src/",
]

# RPC endpoints
[rpc_endpoints]
sepolia = "${RPC_SEPOLIA}"
bsc = "${RPC_BSC}"

# Etherscan API keys
[etherscan]
sepolia = { key = "${API_ETHERSCAN}" }
bsc = { key = "${API_ETHERSCAN}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
